修改 配置启动器 一项的图片和注释
bs-community/blessing-skin-manual pull request #61
Opened 2022-10-07 00:33 UTC by zkitefly

2022-10-09 02:02 UTC, g-plane requested changes
- 第一张图太大，加载时间太长。
- 能在文档里用文字解释的就不要写在图片里，也不需要事无巨细地全部在图片中体现。能表达出关键信息就够了。

2022-10-09 02:03 UTC, g-plane commented on man/yggdrasil-api/authlib-injector.md
> +*其他启动器请自行寻找相关文档进行配置*
```suggestion
```

2022-10-14 11:08 UTC, zkitefly commented
> * 第一张图太大，加载时间太长。
> * 能在文档里用文字解释的就不要写在图片里，也不需要事无巨细地全部在图片中体现，能表达出关键信息就够了。

emm，其实我不太想再做一个图片，这个图片是仿照以前的图片做的

2022-10-14 11:45 UTC, g-plane commented
- 图片大小尽量控制在 1MB 以内
- 文字不要嵌在图片里，应该写在文档中

2022-10-14 11:46 UTC, zkitefly commented
> * 图片大小尽量控制在 1MB 以内
> * 文字不要嵌在图片里，应该写在文档中

好，大概明天发个commit

2022-10-15 03:32 UTC, g-plane approved these changes

2022-10-15 03:33 UTC, merged