修改 「样例 Yggdrasil 认证服务器」地址
bs-community/blessing-skin-manual pull request #62
Opened 2022-10-15 05:11 UTC by zkitefly

根据 https://github.com/yushijinhun/yggdrasil-mock/wiki/%E6%BC%94%E7%A4%BA%E7%AB%99%E7%82%B9 修改

2022-10-15 15:03 UTC, g-plane requested changes

2022-10-15 15:03 UTC, g-plane commented on man/yggdrasil-api/troubleshooting.md
> +*另一个可用的样例 API 是 `https://mcskin.littleservice.cn/api/yggdrasil`，您可以使用 [LittleSkin]() 的账号进行登录测试。*
```suggestion
另一个可用的样例 API 是 `https://mcskin.littleservice.cn/api/yggdrasil`，您可以使用 LittleSkin 的账号进行登录测试。
```

2023-01-04 08:38 UTC, g-plane commented
ping @zkitefly

2023-01-14 10:57 UTC, zkitefly commented
抱歉现在才想起来

2023-01-14 15:03 UTC, g-plane commented on man/yggdrasil-api/troubleshooting.md
> +|deadmau5@example.com|123456|
```suggestion
|deadmau5@example.com|123456|

```

2023-01-14 15:03 UTC, g-plane approved these changes

2023-01-14 15:04 UTC, merged